# Generated by Django 2.1.3 on 2018-12-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20181221_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category1',
        ),
    ]
